const mensagens = [
    'viva a indieweb!!',
    'rm -rf /*',
    'esse site foi feito por uma pessoa como você!',
    './lexpdev.sh',
    ':(){:|:&};:',
    'meow',
    'ᕕ( ᐛ )ᕗ',
    'fazer site é difícil hein...',
    '>··<',
    'Would you. Could you. On a train?',
    'você deveria tentar criar o seu próprio site',
    'meowgic is real!',
    'agora é a melhor época para fazer arte. COMECE AGORA!!',
    'pare de atualizar a pagina! >:(',
    'tem gente que realmente lê isso?',
    'seja livre e use linux!',
    '"XD"',
    "'w'",
    '🏳️‍⚧️ direitos trans são direitos humanos! 🏳️‍⚧️',
    'você tem o potencial de ser uma pessoa incrível!',
    'd  k  d d k  d ddk d k d ddk',
    'casualmente escutando um breakcore de 320bpm',
    'pu-pweh',
];
document.getElementById('mensagem').textContent = mensagens[Math.floor(Math.random() * mensagens.length)];
